#!/usr/bin/env bash
# Run the repo's playbooks against the Vagrant VM, with the Ansible pinned
# by this repository. Playbook paths are relative to ubuntu/, like run.sh.
#
#   ./debug.sh                                  # the full run, like ubuntu/run.sh
#   ./debug.sh playbooks/playbook-media.yml     # a single playbook
#   ./debug.sh playbooks/playbook-media.yml -vv # extra args pass through
#
# TARGET_USER (default: vagrant) selects the account the playbooks configure,
# overriding the SUDO_USER/USER lookup in group_vars/all/config.yml, which
# would otherwise resolve to the account on this machine. Pass vault flags
# as extra args when group_vars/all/vault.yml exists, e.g. --ask-vault-pass.
set -euo pipefail
cd "$(dirname "$0")"

ssh_config="$PWD/.vagrant-ssh-config"
inventory="$PWD/inventory.ini"

# Regenerated on every run. When the libvirt daemon is unreachable (e.g. the
# shell lacks the libvirt group until the next login), fall back to the config
# from the last successful run; the VM's address does not change while it runs.
# Generated via a temp file so a failure never truncates the fallback.
ssh_config_tmp="$(mktemp)"
if vagrant ssh-config >"$ssh_config_tmp" 2>/dev/null; then
  mv "$ssh_config_tmp" "$ssh_config"
else
  rm -f "$ssh_config_tmp"
  if [[ ! -s "$ssh_config" ]]; then
    echo "vagrant cannot reach libvirt and no $ssh_config exists yet." >&2
    echo "Is the VM up, and is this shell in the libvirt group?" >&2
    exit 1
  fi
  echo "warning: reusing $ssh_config (vagrant cannot reach libvirt)" >&2
fi

target_user="${TARGET_USER:-vagrant}"
# playbook-preflight.yml resolves this with getent in the full run; a playbook
# run on its own never executes it, so provide it here.
target_user_home="${TARGET_USER_HOME:-/home/$target_user}"
playbook="${1:-playbook.yml}"
# Anything else before it (e.g. "./debug.sh --ask-vault-pass") is a flag:
# keep the default playbook and let it pass through to ansible-playbook.
if [[ $# -gt 0 && $1 == -* ]]; then
  playbook="playbook.yml"
else
  [[ $# -gt 0 ]] && shift
fi

ansible="../.venv/bin/ansible-playbook"
if [[ ! -x "$ansible" ]]; then
  ansible="$(command -v ansible-playbook)" || {
    echo "ansible-playbook not found. Run 'uv sync' in the repository root." >&2
    exit 1
  }
fi

# The VM's port and key location are provider- and run-specific; the ssh
# config vagrant just generated holds them, so the inventory only points
# ssh at it. Regenerated on every run, never committed.
cat >"$inventory" <<EOF
# Generated by debug.sh; do not edit.
[vagrant]
default ansible_connection=ssh ansible_user=vagrant ansible_ssh_common_args='-F $ssh_config'
EOF

# Run from ubuntu/ so ansible.cfg applies (become_plugins, result_format) and
# group_vars/all is found next to the playbook. The -i flag overrides the
# ansible.cfg inventory that points at this machine.
cd ../ubuntu
exec "$ansible" -i "$inventory" \
  -e "target_user=$target_user" \
  -e "target_user_home=$target_user_home" \
  "$@" "$playbook"
