---
- hosts: all
  become: true

  tasks:
    - name: Install Rawtherapee
      apt:
        name:
          - rawtherapee
        state: present
    - name: Install Darktable
      apt:
        name:
          - darktable
        state: present
